Functionalities and configuration to use Oracle in layers upload service
PEM-Humboldt/herramienta-resiliencia-servidor pull request #24
Opened 2022-08-29 13:07 UTC by ManuelStardust

Include functionalities and configuration in node sever and docker containers to upload thematic information to Oracle in layers upload service.

- Install oracle client in docker container.
- Install dbf read library to nodejs
- Install oracle conection library to nodejs
- Include sscript to read dbf file and load to oracle
- Update enviroment variables

2022-08-29 15:41 UTC, erikasv commented on docker-compose.dev.yml
> +     - server_net
Por favor borra las lineas en blanco de esta sección

2022-08-29 16:00 UTC, ManuelStardust commented on docker-compose.dev.yml
> +     - server_net
Fixed

2022-08-29 16:00 UTC, ManuelStardust commented on docker-compose.yml
> +      - 1521:1521
Fixed

2022-08-29 16:44 UTC, erikasv requested changes
- Por favor correr prettier para corregir el formato
- El problema del cliente de Oracle persiste, ahora puedo intentar diagnosticarlo a ver si tengo más información
![image](https://user-images.githubusercontent.com/1734998/187251829-818ede51-4d66-47e2-9011-391efbb49aa7.png)

2022-08-29 16:44 UTC, erikasv commented on src/utils/dbf2oracle.js
> +  let connection
Es mejor inicializar las variable, en este caso se puede hacer directamente con su valor y debería ser un `const` ya que no cambia luego

2022-08-29 16:44 UTC, erikasv commented on src/utils/dbf2oracle.js
> +  let records
dales un valor inicial

2022-08-29 16:44 UTC, erikasv commented on src/utils/dbf2oracle.js
> +      let value;
esta variable no está siendo usada

2022-08-29 16:44 UTC, erikasv commented on src/utils/dbf2oracle.js
> +    logger.info(err);
lanza el error después de loguearlo

2022-08-29 16:44 UTC, erikasv commented on src/utils/dbf2oracle.js
> +  const { DB_SYSTEM, ORACLE_HOST, ORACLE_PORT, DB_USER, DB_NAME, DB_PASSWORD } = process.env;
`DB_SYSTEM` no está siendo usado

2022-08-29 16:44 UTC, erikasv commented on src/utils/dbf2oracle.js
> +    logger.info(err);
lanza el error después de loguearlo

2022-08-29 16:44 UTC, erikasv commented on src/utils/dbf2oracle.js
> +    let resultDrop = await connection.execute(queryDrop)
`resultDrop` y `resultCreate` no están siendo usados

2022-08-29 16:44 UTC, erikasv commented on src/utils/dbf2oracle.js
> +    logger.info(err);
lanza el error después de loguearlo

2022-08-29 16:44 UTC, erikasv commented on src/utils/dbf2oracle.js
> +      const result = await connection.execute(query, values,{ autoCommit: true});
`result` no se usa despues.

Y lanza el error del catch después de loguearlo

2022-08-29 16:44 UTC, erikasv commented on src/utils/dbf2oracle.js
> +  let arrayFields = [];
con javascript usamos snake_case en lugar de camelCase (creo que se me pasó cuando se hizo lo del workspace :sweat_smile: )

2022-08-29 17:40 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +      for (let field of fields) {
De acuerdo, mucho mejor

2022-08-29 20:43 UTC, ManuelStardust commented on src/app.js
> +      }
Solved

2022-08-29 20:43 UTC, ManuelStardust commented on src/utils/database_utils.js
> +  if(DB_SYSTEM=='oracle'){
Solved

2022-08-29 20:43 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +  let connection
Solved

2022-08-29 20:44 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +  let records
Solved

2022-08-29 20:44 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +    let resultDrop = await connection.execute(queryDrop)
Solved

2022-08-29 20:44 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +  let arrayFields = [];
Solved

2022-08-29 21:40 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +  });
Solved

2022-08-29 21:40 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +    logger.info(err);
Solved

2022-08-29 21:40 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +    logger.info(err);
Solved

2022-08-29 21:40 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +      const result = await connection.execute(query, values,{ autoCommit: true});
Solved

2022-08-29 21:46 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +    dbf = await DBFFile.open(file, { encoding: 'UTF-8'}); //Ruta al archivo dbf
Solved

2022-08-29 21:46 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +    fields.map(function(f){
Solved

2022-08-29 21:46 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +      let value;
Solved

2022-08-29 21:46 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +      for (let field of fields) {
Solved

2022-08-29 21:47 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +  let connection
Solved

2022-08-29 21:47 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +  const { DB_SYSTEM, ORACLE_HOST, ORACLE_PORT, DB_USER, DB_NAME, DB_PASSWORD } = process.env;
Solved

2022-08-29 21:47 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +    logger.info(err);
Solved

2022-08-29 21:50 UTC, ManuelStardust commented
> 

Prettier ejecutado

2022-08-29 22:43 UTC, erikasv requested changes

2022-08-29 22:43 UTC, erikasv commented on src/utils/database_utils.js
> +  let dbfPath = folder + "/" + dbf_file;
Usa [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) en lugar de concatenar strings

2022-08-29 22:43 UTC, erikasv commented on src/utils/database_utils.js
> +  shp_file = files.find((file) => file.endsWith(".shp"));
Esto también debe ir en un try-catch (como estaba)

2022-08-29 22:43 UTC, erikasv commented on src/utils/database_utils.js
> +  }
Mejor deja sólo el if, sin los try-catch, acá no se hace nada con los resultados de estos llamados y los errores se loguean en pasos anteriores, así que se puede dejar elevar el error sin problema.

Pero hay que ponerles el await o el error no se responderá en el endpoint, como actualmente ocurre

2022-08-29 22:43 UTC, erikasv commented on src/utils/database_utils.js
> +  }
Ya que tampoco se hace nada con estos datos y el error se loguea en dbf2oracle se puede retornar el llamado a la función y ya. Si no se retorna se debe poner el await

2022-08-29 22:45 UTC, erikasv commented on docker-compose.yml
> +     - server_net
la indentación está mal aqui

2022-08-29 22:45 UTC, erikasv commented on docker-compose.dev.yml
> +     - server_net
la indentación está mal aqui

2022-08-30 13:18 UTC, ManuelStardust commented on docker-compose.yml
> +     - server_net
Solucionado

2022-08-30 13:19 UTC, ManuelStardust commented on docker-compose.dev.yml
> +     - server_net
Solucionado

2022-08-30 13:29 UTC, ManuelStardust commented on src/utils/database_utils.js
> +  let dbfPath = folder + "/" + dbf_file;
Solucionado

2022-08-30 13:29 UTC, ManuelStardust commented on src/utils/database_utils.js
> +  shp_file = files.find((file) => file.endsWith(".shp"));
Solucionado

2022-08-30 14:19 UTC, erikasv requested changes
Ya casi xD, estos ya son detallitos menores

2022-08-30 14:19 UTC, erikasv commented on src/utils/dbf2oracle.js
> +    });
El uso de map aquí es incorrecto, map se debe usar para transformar el arreglo, pero aquí lo único que se desea es procesar todos los elementos. Además ese async-await no tienen efecto en esta sentencia (basta con imprimir en el log un índice para notarlo).

Si de verdad es necesario que se ejecuten secuencialmente se debe usar un [for await...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of), pero si no, basta con un forEach

2022-08-30 14:19 UTC, erikasv commented on src/utils/database_utils.js
> +  let dbfPath = `${folder}/${dbf_file}`;
Esta variable no se modifica posteriormente, usar const.

2022-08-30 14:19 UTC, erikasv commented on src/utils/dbf2oracle.js
> +  records.map(function (record) {
cambia este `function (record) {...` por un arrow function (`(record) => {...`)

2022-08-30 14:19 UTC, erikasv commented on src/utils/dbf2oracle.js
> +  records.map(function (record) {
En este caso tampoco es apropiado el uso de `map`, mejor usar `forEach`

2022-08-30 14:19 UTC, erikasv commented on src/utils/dbf2oracle.js
> +    logger.info(`Conexión establecida a la base de datos Oracle`);
En este y en todos los casos donde no se usen variables, usar comillas dobles (pueden ser simples y el prettier luego las cambia xD, pero es que esta del template no la cambia)

2022-08-30 16:39 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +    });
Solucionado

2022-08-30 16:40 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +    });
Se cambio la funcion de insert, para poder hacer la carga del bloque de registros en una sola transacción y de esta manera si atrapa los errores y los muestra en el endpoint

2022-08-30 16:40 UTC, ManuelStardust commented on src/utils/database_utils.js
> +  let dbfPath = `${folder}/${dbf_file}`;
Solucionado

2022-08-30 16:48 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +  records.map(function (record) {
Solucionado

2022-08-30 16:48 UTC, ManuelStardust commented on src/utils/dbf2oracle.js
> +    logger.info(`Conexión establecida a la base de datos Oracle`);
Solucionado

2022-08-30 19:43 UTC, erikasv approved these changes

2022-08-30 20:52 UTC, merged